### ISSUE TITLE
Support for ruby2.7?

### ISSUE THREAD

**Issue by utkarsh2102** [ruby/psych#431]
Hi,

Ruby 2.7 was out last year in December. I am not sure if ruby-psych works with that, does it?
If not, could you possible make that happen?

Also, the last release was in October'18, maybe it's time for a release again, please? :)

**Comment by utkarsh2102** [comment]
```
<<PKGBUILDDIR>>/test/psych/test_coder.rb:48:in `<class:Represent>': undefined method `yaml_tag' for Psych::TestCoder::Represent:Class (NoMethodError)
	from /<<PKGBUILDDIR>>/test/psych/test_coder.rb:47:in `<class:TestCoder>'
	from /<<PKGBUILDDIR>>/test/psych/test_coder.rb:5:in `<module:Psych>'
	from /<<PKGBUILDDIR>>/test/psych/test_coder.rb:4:in `<top (required)>'
	from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	from /usr/lib/ruby/vendor_ruby/rake/rake_test_loader.rb:17:in `block in <main>'
	from /usr/lib/ruby/vendor_ruby/rake/rake_test_loader.rb:5:in `select'
	from /usr/lib/ruby/vendor_ruby/rake/rake_test_loader.rb:5:in `<main>'
rake aborted!
```

**Comment by tenderlove** [comment]
Psych works fine on Ruby 2.7.  Is there a specific problem you are having?  I see your exception, but I don't know how to reproduce it.  Thanks.

**Comment by deivid-rodriguez** [comment]
This turned out to be an issue with `rubygems` that should be fixed by https://github.com/rubygems/rubygems/pull/3124.

It affected Debian ruby packagers, because of the way they use the `-I`option, and the error can be "simulated" by editing the `test/psych/helper.rb` file like this:

```diff
diff --git a/test/psych/helper.rb b/test/psych/helper.rb
index 9348457..f8f7050 100644
--- a/test/psych/helper.rb
+++ b/test/psych/helper.rb
@@ -4,7 +4,7 @@ require 'stringio'
 require 'tempfile'
 require 'date'
 
-require 'psych'
+require 'psych.so'
 
 module Psych
   superclass = if defined?(Minitest::Test)
```

Anyways, I think this issue can be closed.
